<?php
function wysiwyg_blocktranslation_form_alter(&$form, &$form_state, $form_id){
  if($form_id == 'i18n_string_translate_page_form'){
    foreach($form['strings']['all'] as $name => $field){
          if(
              preg_match('/blocks:block:[0-9]+:body/i',$name) ||
	      preg_match('/taxonomy:term:[0-9]+:description/i' , $name)
          ) {
              // Change textarea to text_format
              $form['strings']['all'][$name]['#type'] = 'text_format';
              $form['strings']['all'][$name]['#description'] = '<br/>';
          }
      }
      $form['#submit'] = array_merge(array('wysiwyg_blocktranslation_string_translate_page_form_submit'), $form['#submit']);
  }
}

function wysiwyg_blocktranslation_string_translate_page_form_submit($form, &$form_state) {
  // Remove wysiwyg format because i18n cant handle it
  foreach($form_state['values']['strings'] as $name => $field) {
    if(
        preg_match('/blocks:block:[0-9]+:body/i', $name) ||
        preg_match('/taxonomy:term:[0-9]+:description/i', $name)
    ) {
      unset($form_state['values']['strings'][$name]['format']);
    }
  }
}
